name: mon premier workflow
on: [push]

jobs : 
  build : 
    runs-on: ubuntu-latest
    steps:
    - name : Hello
      run: echo "Hello !!!"
    - name : "LS"
      run: ls -l
    - name: "use_action"
      uses: actions/checkout@V4
